apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cuti
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-cuti
  template:
    metadata:
      labels:
        app: app-cuti
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
